# Generated by Django 4.2.2 on 2024-08-01 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogs', '0002_dog_latitude_dog_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='breed_photos/'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
