# Generated by Django 4.2.2 on 2024-09-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_breed_default_image_dog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='default_image',
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, default='/static/images/dog_logo.png', null=True, upload_to='dog_photos/'),
        ),
    ]
